name: PR Review Request

on:
  pull_request:
    types: [ opened ]

jobs:
  pr-review-request:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.body, '/s ')
    steps:
      - name: Set Reviewers
        id: variables
        shell: python
        run: |
          import re, os
          
          members = {
            '이보람': '<@U026RSQ3CMR>' # 슬랙 멤버 ID
          };
          
          prBody = """${{ github.event.pull_request.body }}"""
          matched = re.search(r'(?:\/s)\s+(([가-힣]+ *,? *)+)', prBody) # '/s ' 다음에 위치한 사람 이름만 추출
          
          reviewers = ""
          
          if matched:
            names = matched.group(1).split(",") # (1)번 그룹을 ',' 을 기준으로 분리 - (1)번 그룹은 위에서 추출한 사람 이름 목록이다.
            reviewers += "\\n".join(map(lambda name: members[name.strip()], names)) # 멤버 ID를 `\n` 로 join
          
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
            print(f'reviewers={reviewers}', file=fh)

      - name: PR Review Notification
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_WEBHOOK_URL: 'https://hooks.slack.com/services/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'
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "text": "Pull Request 알림:  ${{ github.event.repository.name }}",
              "channel": "U026RSQ3CMR",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*PR 알림   |   ${{ github.event.repository.name }}*"
                  }
                },
                {
                  "type": "section",
                  "text": [
                    {
                      "type": "mrkdwn",
                      "text": "*PR 제목*\n<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*작성자*\n${{ github.event.pull_request.user.login }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Reviewers*\n${{ steps.variables.outputs.reviewers }}"
                    }
                  ]
                }
              ]
            }
